services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    volumes:
      - ./php-app:/var/www/html
    environment:
      DB_HOST: db
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_PORT: ${MYSQL_TCP_PORT}
      APP_KEY: ${LARAVEL_APP_KEY}
      API_KEY: ${LARAVEL_API_KEY}
      API_KEY_TESTING: ${LARAVEL_API_KEY_TESTING}
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
      db-testing:
        condition: service_healthy

  web:
    image: nginx:alpine
    container_name: nginx-web
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro 
      - ./php-app:/var/www/html
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 3

  db-testing:
    image: mysql:8.0
    container_name: mysql-db-testing
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
    networks:
      - app-network
    tmpfs:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  db-data: